# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56342062ead5f73ae76ae681590e83661a84bc838c592bd3c219ac16023e7b22bd13dfc66181e705dd606e4cb55890213eb2c11e296f3c6e76745ab7e0067f50

test:
  secret_key_base: 29601f5a1b85a31a0d099200b9499410099036aa3505f7564ce0ed90132d48a3efc30d0075e755138251e49a2f72d2eeecef4a4e58e863790fb86747d5c60237

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
